frContentJson = JSON.parse(`
{
	"global-menu" 						: "Paramètres Globaux",
	"videos-menu" 						: "Paramètres Vidéo",
	"sounds-menu" 						: "Paramètres Son",
	"bot-commands-menu" 				: "Commandes du Bot",
	"export-menu" 						: "Exporter",
	"language-menu"						: "Langage",
	"english-menu"						: "English",
	"french-menu"						: "Français",
	"add-button"						: "Ajouter",
	"legend-title"						: "Légende",
	"global-title"						: "Paramètre Globaux",
	"channel-label"						: "Chaîne Twitch",
	"channel-legend"					: "Nom de la chaîne. Ce programme écoutera le chat de cette chaîne pour y repérer les commandes commençant par un !.<br><b>Obligatoire pour le fonctionnement de ce programme.</b>",
	"chat-user-label"					: "Utilisateur du Chat",
	"chat-user-legend"					: "Nom de l'utilisateur (peut être votre nom de compte, ou le nom d'un compte de bot créé spécifiquement à cet effet) qui écrira dans le chat.<br><b>Ce paramètre n'est requis que pour l'utlisation des 'Commandes du Bot'.</b>",
	"chat-oauth-label"					: "Clé d'authentification Oauth",
	"chat-oauth-legend"					: "Connectez vous au lien: <a href=\\"https://twitchapps.com/tmi/\\" target=\\"_blank\\">[Obtenir votre clé d'authentification]</a> avec le compte spécifié comme 'Chat User' pour récupérer sa clé d'authentification.<br><b>Ne fournissez jamais cette clé à personne d'autre.</b><br>En cas de doute, retourner sur le lien pour générer une nouvelle clé et invalider l'ancienne.<br><b>Ce paramètre n'est requis que pour l'utlisation des 'Commandes du Bot'.</b>",
	"pause-videos-label"				: "Commande de mise en pause des Vidéos",
	"pause-videos-legend"				: "Chaîne de caractères de la commande pour mettre les vidéos en pause. Cette commande ne répondra qu'au propriétaire de la chaîne.",
	"resume-videos-label"				: "Commande de reprise des Vidéos",
	"resume-videos-legend"				: "Chaîne de caractères de la commande pour reprendre les vidéos. Cette commande ne répondra qu'au propriétaire de la chaîne.",
	"delay-videos-label"				: "Délai Global des Vidéos",
	"delay-videos-legend"				: "Délai minimum entre deux vidéos en secondes. Si une vidéo est d'une durée plus longue que ce délai, sa durée sera utilisée à la place de cette valeur.",
	"videos-title"						: "Vidéos",
	"video-command-title"				: "Commande",
	"video-command-label"				: "Commande",
	"video-command-legend"				: "Commande lue après un ! qui déclenche la vidéo.",
	"video-file-title"					: "Nom du fichier",
	"video-file-label"					: "Nom du fichier",
	"video-file-legend"					: "Nom du fichier associé dans le dossier 'videos'",
	"video-right-title"					: "Droits",
	"video-right-label"					: "Droits",
	"video-right-legend"				: "Qui peut utiliser cette commande (Streamer·euse > Modérateur·ice + Streamer·euse > VIP + précédents > Tout le monde)",
	"video-delay-title"					: "Délai",
	"video-delay-label"					: "Délai",
	"video-delay-legend"				: "Délai minimum entre deux utilisation de cette commande, en secondes.",
	"video-volume-title"				: "Volume",
	"video-volume-label"				: "Volume",
	"video-volume-legend"				: "Volume de la vidéo, valeur comprise entre 0 et 1. ( utilisez le '.' pour délimiter les décimales )",
	"pause-sounds-label"				: "Commande de mise en Pause des Sons",
	"pause-sounds-legend"				: "Chaîne de caractères de la commande pour mettre les sons en pause. Cette commande ne répondra qu'au propriétaire de la chaîne.",
	"resume-sounds-label"				: "Commande de Reprise des Sons",
	"resume-sounds-legend"				: "Chaîne de caractères de la commande pour redémarrer les sons. Cette commande ne répondra qu'au propriétaire de la chaîne.",
	"delay-sounds-label"				: "Délai Global des Sons",
	"delay-sounds-legend"				: "Délai minimum entre deux sons en secondes. Si un son est d'une durée plus longue que ce délai, sa durée sera utilisée à la place de cette valeur.",
	"sounds-title"						: "Sons",
	"sound-command-title"				: "Commande",
	"sound-command-label"				: "Commande",
	"sound-command-legend"				: "Commande lue après un ! qui déclenche le son.",
	"sound-file-title"					: "Nom du fichier",
	"sound-file-label"					: "Nom du fichier",
	"sound-file-legend"					: "Nom du fichier associé dans le dossier 'sounds'",
	"sound-right-title"					: "Droits",
	"sound-right-label"					: "Droits",
	"sound-right-legend"				: "Qui peut utiliser cette commande (Streamer·euse > Modérateur·ice + Streamer·euse > VIP + précédents > Tout le monde)",
	"sound-delay-title"					: "Délai",
	"sound-delay-label"					: "Délai",
	"sound-delay-legend"				: "Délai minimum entre deux utilisation de cette commande, en secondes.",
	"sound-volume-title"				: "Volume",
	"sound-volume-label"				: "Volume",
	"sound-volume-legend"				: "Volume du son, valeur comprise entre 0 et 1. ( utilisez le '.' pour délimiter les décimales )",
	"display-all-video-label" 			: "Commande récapitulatrice des vidéos",
	"display-all-video-legend"			: "Cette commande fera écrire au bot la liste des commandes de vidéos disponibles à l'utilisateur.",
	"display-all-sound-label" 			: "Commande récapitulatrice des sons",
	"display-all-sound-legend"			: "Cette commande fera écrire au bot la liste des commandes de sons disponibles à l'utilisateur.",
	"display-all-bot-command-label" 	: "Commande récapitulatrice des commandes du bot",
	"display-all-bot-command-legend"	: "Cette commande fera écrire au bot la liste des commandes de bot disponibles à l'utilisateur.",
	"bot-commands-title"				: "Bot Commands",
	"bot-command-string-title"			: "Commande",
	"bot-command-string-label"			: "Commande",
	"bot-command-string-legend"			: "Chaîne de caractères de la commande pour déclencher la réponse du bot.",
	"bot-command-output-title"			: "Output",
	"bot-command-output-label"			: "Output",
	"bot-command-output-legend"			: "Réponse du bot à cette commande dans le chat. L'utilisation de '{username}' comme variable à laquelle sera substitué le nom de l'utilisateur ayant lancé la commande est possible.<br>Si vous souhaitez des commandes multi parties, il vous suffit d'utiliser la même chaîne de caractère remplaçable dans la chaîne de la commande et dans le message du bot. i.e. '$1' ou '{a}' etc... ( voir les exemples pré-remplis ).",
	"bot-command-right-title"			: "Droits",
	"bot-command-right-label"			: "Droits",
	"bot-command-right-legend"			: "Qui peut utiliser cette commande (Streamer·euse > Modérateur·ice + Streamer·euse > VIP + précédents > Tout le monde)",
	"right-option-streamer"				: "Streamer·euse",
	"right-option-moderator"			: "Moderateur·ice",
	"right-option-vip"					: "VIP",
	"right-option-everyone"				: "Tout le monde"
}
`);